version: '3'

services:
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
      - "3000:3000"
    restart: always

  frontend:
    image: nginx
    container_name: frontend
    depends_on:
      - proxy
      - backend
    volumes:
      - ./frontend/content:/usr/share/nginx/html
    restart: always

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - proxy
    volumes: 
      - ./backend/:/src/app
    working_dir: /src/app
    restart: always
